// PAST TENSE ACTIONS
const MEMBER_INSERTED = 'MEMBER_INSERTED'
const MEMBER_UPDATED = 'MEMBER_UPDATED'
const MEMBER_REMOVED = 'MEMBER_REMOVED'
const MEMBER_DELETED = 'MEMBER_DELETED'

// PRESENT TENSE ACTIONS
const ADD_MEMBER = 'ADD_MEMBER'
const EDIT_MEMBER = 'EDIT_MEMBER'
const REMOVE_MEMBER = 'REMOVE_MEMBER'
const DELETE_MEMBER = 'DELETE_MEMBER'
const GET_MEMBER_FRIENDSLIST = 'GET_MEMBER_FRIENDSLIST'
const GET_MEMBER_BACKGROUND = 'GET_MEMBER_BACKGROUND'

export const Events = {
  MEMBER_INSERTED,
  MEMBER_UPDATED,
  MEMBER_DELETED,
  MEMBER_REMOVED,
  ADD_MEMBER,
  EDIT_MEMBER,
  REMOVE_MEMBER,
  DELETE_MEMBER,
  GET_MEMBER_FRIENDSLIST,
  GET_MEMBER_BACKGROUND,
}
