// PAST TENSE ACTIONS
export const MEMBER_INSERTED = 'MEMBER_INSERTED'
export const MEMBER_UPDATED = 'MEMBER_UPDATED'
export const MEMBER_REMOVED = 'MEMBER_REMOVED'
export const MEMBER_DELETED = 'MEMBER_DELETED'

// PRESENT TENSE ACTIONS
export const ADD_MEMBER = 'ADD_MEMBER'
export const EDIT_MEMBER = 'EDIT_MEMBER'
export const REMOVE_MEMBER = 'REMOVE_MEMBER'
export const DELETE_MEMBER = 'DELETE_MEMBER'
export const GET_MEMBER_FRIENDSLIST = 'GET_MEMBER_FRIENDSLIST'
export const GET_MEMBER_BACKGROUND = 'GET_MEMBER_BACKGROUND'
