export const SQUAD_INSERTED = 'SQUAD_INSERTED'
export const SQUAD_UPDATED = 'SQUAD_UPDATED'
export const SQUAD_DELETED = 'SQUAD_DELETED'
export const SQUAD_REMOVED = 'SQUAD_REMOVED'
export const SQUAD_RENAMED = 'SQUAD_RENAMED'
export const SQUAD_TRANSFER = 'SQUAD_TRANSFER'
export const REMOVE_SQUAD = 'REMOVE_SQUAD'
export const EDIT_SQUAD = 'EDIT_SQUAD'
export const DELETE_SQUAD = 'DELETE_SQUAD'
export const ADD_SQUAD = 'ADD_SQUAD'
export const SQUAD_MEMBER_TRANSFER = 'SQUAD_MEMBER_TRANSFER'

export const Events = {
  SQUAD_INSERTED,
  SQUAD_DELETED,
  SQUAD_UPDATED,
  SQUAD_REMOVED,
  SQUAD_RENAMED,
  SQUAD_TRANSFER,
  REMOVE_SQUAD,
  EDIT_SQUAD,
  DELETE_SQUAD,
  ADD_SQUAD,
  SQUAD_MEMBER_TRANSFER,
}
